# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from add_remove import Ui_Edit
from adminstatus import Ui_Status
import admin_panel,sys


class Ui_Admin_Panel(object):
    def openWindow(self):
        self.window = QtWidgets.QDialog()
        self.ui = Ui_Edit()
        self.ui.setupUi(self.window)
        self.window.show()
    def openWindow2(self):
        self.window = QtWidgets.QDialog()
        self.ui = Ui_Status()
        self.ui.setupUi(self.window)
        self.window.show()
    def setupUi(self, Admin_Panel):
        Admin_Panel.setObjectName("Admin_Panel")
        Admin_Panel.resize(1200, 700)
        Admin_Panel.setStyleSheet("background: #FFFFFF;")
        Admin_Panel.setSizeGripEnabled(False)
        self.frame = QtWidgets.QFrame(Admin_Panel)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1201, 80))
        self.frame.setStyleSheet("background: #D8F8E8;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lbl_jp = QtWidgets.QLabel(self.frame)
        self.lbl_jp.setGeometry(QtCore.QRect(490, 10, 311, 51))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_jp.setFont(font)
        self.lbl_jp.setStyleSheet("color: #00000\n"
"")
        self.lbl_jp.setObjectName("lbl_jp")
        self.frm_cmp = QtWidgets.QFrame(Admin_Panel)
        self.frm_cmp.setGeometry(QtCore.QRect(291, 222, 271, 261))
        self.frm_cmp.setStyleSheet("background: #D8F8E8;\n"
"border-radius: 20px;")
        self.frm_cmp.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_cmp.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_cmp.setObjectName("frm_cmp")
        self.img_cmp = QtWidgets.QLabel(self.frm_cmp)
        self.img_cmp.setGeometry(QtCore.QRect(60, 40, 141, 121))
        self.img_cmp.setStyleSheet("image: url(:/all/img/Add Remove.png);")
        self.img_cmp.setObjectName("img_cmp")
        self.btn_cmp = QtWidgets.QPushButton(self.frm_cmp,clicked = lambda: self.openWindow())
        self.btn_cmp.setGeometry(QtCore.QRect(40, 190, 191, 28))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_cmp.setFont(font)
        self.btn_cmp.setStyleSheet("color: #0000;\n"
"\n"
"")
        self.btn_cmp.setObjectName("btn_cmp")
        self.frm_civil = QtWidgets.QFrame(Admin_Panel)
        self.frm_civil.setGeometry(QtCore.QRect(630, 222, 271, 261))
        self.frm_civil.setStyleSheet("background: #D8F8E8;\n"
"border-radius: 20px;\n"
"")
        self.frm_civil.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_civil.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_civil.setObjectName("frm_civil")
        self.img_civil = QtWidgets.QLabel(self.frm_civil)
        self.img_civil.setGeometry(QtCore.QRect(70, 40, 121, 111))
        self.img_civil.setStyleSheet("image: url(:/all/img/view_status_User.png);")
        self.img_civil.setObjectName("img_civil")
        self.btn_civil = QtWidgets.QPushButton(self.frm_civil,clicked = lambda: self.openWindow2())
        self.btn_civil.setGeometry(QtCore.QRect(40, 180, 191, 28))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_civil.setFont(font)
        self.btn_civil.setStyleSheet("color: #00000;\n"
"")
        self.btn_civil.setObjectName("btn_civil")
        self.btn_logout = QtWidgets.QPushButton(Admin_Panel)
        self.btn_logout.setGeometry(QtCore.QRect(50, 630, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_logout.setFont(font)
        self.btn_logout.setStyleSheet("background-color:#D8F8E8;")
        self.btn_logout.setObjectName("btn_logout")

        self.retranslateUi(Admin_Panel)
        QtCore.QMetaObject.connectSlotsByName(Admin_Panel)

    def retranslateUi(self, Admin_Panel):
        _translate = QtCore.QCoreApplication.translate
        Admin_Panel.setWindowTitle(_translate("Admin_Panel", "Dialog"))
        self.lbl_jp.setText(_translate("Admin_Panel", "Admin Panel"))
        self.img_cmp.setText(_translate("Admin_Panel", "<html><head/><body><p><br/></p></body></html>"))
        self.btn_cmp.setText(_translate("Admin_Panel", "Add /Remove "))
        self.img_civil.setText(_translate("Admin_Panel", "<html><head/><body><p><br/></p></body></html>"))
        self.btn_civil.setText(_translate("Admin_Panel", "View Status"))
        self.btn_logout.setText(_translate("Admin_Panel", "Logout"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Admin_Panel = QtWidgets.QDialog()
    ui = Ui_Admin_Panel()
    ui.setupUi(Admin_Panel)
    Admin_Panel.show()
    sys.exit(app.exec_())
