# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adminstatus.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector as mc
from PyQt5.QtWidgets import QTableWidgetItem


class Ui_Status(object):
    def setupUi(self, Status):
        Status.setObjectName("Status")
        Status.resize(1200, 700)
        Status.setStyleSheet("background: #FFFFFF;")
        Status.setSizeGripEnabled(False)
        self.frame = QtWidgets.QFrame(Status)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1201, 701))
        self.frame.setStyleSheet("background:#D8F8E8;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lbl_appsts = QtWidgets.QLabel(self.frame)
        self.lbl_appsts.setGeometry(QtCore.QRect(380, 17, 491, 51))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_appsts.setFont(font)
        self.lbl_appsts.setStyleSheet("color: rgb(0, 0, 0)\n"
"")
        self.lbl_appsts.setObjectName("lbl_appsts")
        self.comboBox_all = QtWidgets.QComboBox(self.frame)
        self.comboBox_all.setGeometry(QtCore.QRect(970, 20, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_all.setFont(font)
        self.comboBox_all.setObjectName("comboBox_all")
        self.comboBox_all.addItem("")
        self.comboBox_all.addItem("")
        self.comboBox_all.addItem("")
        self.comboBox_all.addItem("")
        self.tbl_sts = QtWidgets.QTableWidget(Status)
        self.tbl_sts.setGeometry(QtCore.QRect(90, 100, 1000, 471))
        self.tbl_sts.setObjectName("tbl_sts")
        self.tbl_sts.setColumnCount(7)
        self.tbl_sts.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_sts.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_sts.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_sts.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_sts.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_sts.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_sts.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_sts.setHorizontalHeaderItem(6, item)
        self.btn_ref = QtWidgets.QPushButton(Status)
        self.btn_ref.setGeometry(QtCore.QRect(70, 610, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_ref.setFont(font)
        self.btn_ref.setObjectName("btn_bck")

        self.retranslateUi(Status)
        QtCore.QMetaObject.connectSlotsByName(Status)

    def retranslateUi(self, Status):
        _translate = QtCore.QCoreApplication.translate
        Status.setWindowTitle(_translate("Status", "Dialog"))
        self.lbl_appsts.setText(_translate("Status", "Application Status "))
        self.comboBox_all.setItemText(0, _translate("Status", "All"))
        self.comboBox_all.setItemText(1, _translate("Status", "Pending"))
        self.comboBox_all.setItemText(2, _translate("Status", "Approved"))
        self.comboBox_all.setItemText(3, _translate("Status", "Rejected"))
        item = self.tbl_sts.horizontalHeaderItem(0)
        item.setText(_translate("Status", "Full name"))
        item = self.tbl_sts.horizontalHeaderItem(1)
        item.setText(_translate("Status", "Company"))
        item = self.tbl_sts.horizontalHeaderItem(2)
        item.setText(_translate("Status", "Job Role"))
        item = self.tbl_sts.horizontalHeaderItem(3)
        item.setText(_translate("Status", "Resume"))
        item = self.tbl_sts.horizontalHeaderItem(4)
        item.setText(_translate("Status", "Total CGPA"))
        item = self.tbl_sts.horizontalHeaderItem(5)
        item.setText(_translate("Status", "Gender"))
        item = self.tbl_sts.horizontalHeaderItem(6)
        item.setText(_translate("Status", "Email"))
        self.btn_ref.setText(_translate("Status", "Refresh"))
        self.btn_ref.clicked.connect(self.select_data)

    def select_data(self):
        try:
            mydb = mc.connect(
                host="localhost",
                user="root",
                password="",
                database="placement"

            )

            mycursor = mydb.cursor()
            mycursor.execute("SELECT * FROM aplctn")

            result = mycursor.fetchall()

            self.tbl_sts.setRowCount(0)

            for row_number, row_data in enumerate(result):
                self.tbl_sts.insertRow(row_number)

                for column_number, data in enumerate(row_data):
                    self.tbl_sts.setItem(row_number,
                                          column_number, QTableWidgetItem(str(data)))


        except mc.Error as e:
            print("Error occured")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Status = QtWidgets.QDialog()
    ui = Ui_Status()
    ui.setupUi(Status)
    Status.show()
    sys.exit(app.exec_())
