# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'idk.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector as mc
from PyQt5.QtWidgets import QMessageBox


class Ui_ui_login(object):
    def setupUi(self, ui_login):
        ui_login.setObjectName("ui_login")
        ui_login.resize(1200, 700)
        ui_login.setStyleSheet("background:#D8F8E8;")
        self.horizontalLayoutWidget = QtWidgets.QWidget(ui_login)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 20, 1121, 151))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.userid = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Typewriter")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.userid.setFont(font)
        self.userid.setObjectName("userid")
        self.horizontalLayout.addWidget(self.userid)
        self.txt_uid = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txt_uid.setFont(font)
        self.txt_uid.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.txt_uid.setObjectName("txt_uid")
        self.horizontalLayout.addWidget(self.txt_uid)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(ui_login)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(40, 200, 1121, 161))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.password = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Typewriter")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.password.setFont(font)
        self.password.setObjectName("password")
        self.horizontalLayout_2.addWidget(self.password)
        self.txt_pass = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.txt_pass.setFont(font)
        self.txt_pass.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.txt_pass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txt_pass.setObjectName("txt_pass")
        self.horizontalLayout_2.addWidget(self.txt_pass)
        self.register_2 = QtWidgets.QPushButton(ui_login)
        self.register_2.setGeometry(QtCore.QRect(400, 610, 369, 41))
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        font.setPointSize(20)
        self.register_2.setFont(font)
        self.register_2.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border: 2px solid #000000;\n"
"border-radius: 20px;\n"
"")
        self.register_2.setObjectName("register_2")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(ui_login)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(40, 390, 1121, 151))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.login = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.login.clicked.connect(self.database)
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        font.setPointSize(18)
        self.login.setFont(font)
        self.login.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border: 2px solid #000000;\n"
"border-radius: 20px;")
        self.login.setObjectName("login")
        self.horizontalLayout_3.addWidget(self.login)
        self.labelresult = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.labelresult.setFont(font)
        self.labelresult.setText("")
        self.labelresult.setObjectName("labelresult")
        self.horizontalLayout_3.addWidget(self.labelresult)

        self.retranslateUi(ui_login)
        QtCore.QMetaObject.connectSlotsByName(ui_login)


    def database(self):
        try:
            usrname = self.txt_uid.text()
            pwd = self.txt_pass.text()

            mydb = mc.connect(
                host="localhost",
                user="root",
                password="",
                database="placement"


            )

            mycursor = mydb.cursor()
            query = "SELECT usrname,pwd from acc where usrname " \
                    "like '"+usrname + "'and pwd like '" \
                    + pwd + "'"
            mycursor.execute(query)
            result = mycursor.fetchone()


            if result == None:
                self.labelresult.setText("Incorrect email or password")

            else:
                self.labelresult.setText("You are logged in")
                mydialog =QMessageBox()
                mydialog.setModal(True)
                mydialog.exec_()


        except mc.Error as e:
            self.labelresult.setText("Error")

    def retranslateUi(self, ui_login):
        _translate = QtCore.QCoreApplication.translate
        ui_login.setWindowTitle(_translate("ui_login", "Dialog"))
        self.userid.setText(_translate("ui_login", "UserID"))
        self.password.setText(_translate("ui_login", "Password"))
        self.register_2.setText(_translate("ui_login", "NEW USER? SIGN IN"))
        self.login.setText(_translate("ui_login", "LOGIN"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ui_login = QtWidgets.QDialog()
    ui = Ui_ui_login()
    ui.setupUi(ui_login)
    ui_login.show()
    sys.exit(app.exec_())
