# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'yedi.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Status(object):
    def setupUi(self, Status):
        Status.setObjectName("Status")
        Status.resize(1200, 700)
        Status.setStyleSheet("background: #FFFFFF;")
        Status.setSizeGripEnabled(False)
        self.frame = QtWidgets.QFrame(Status)
        self.frame.setGeometry(QtCore.QRect(0, -10, 1201, 711))
        self.frame.setStyleSheet("background:#D8F8E8;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lbl_appsts = QtWidgets.QLabel(self.frame)
        self.lbl_appsts.setGeometry(QtCore.QRect(380, 17, 491, 51))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_appsts.setFont(font)
        self.lbl_appsts.setStyleSheet("color: rgb(0, 0, 0)\n"
"")
        self.lbl_appsts.setObjectName("lbl_appsts")
        self.comboBox_all = QtWidgets.QComboBox(self.frame)
        self.comboBox_all.setGeometry(QtCore.QRect(970, 20, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_all.setFont(font)
        self.comboBox_all.setObjectName("comboBox_all")
        self.comboBox_all.addItem("")
        self.comboBox_all.addItem("")
        self.comboBox_all.addItem("")
        self.comboBox_all.addItem("")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(260, 607, 111, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(420, 610, 101, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(552, 610, 101, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.tbl_sts = QtWidgets.QTableWidget(Status)
        self.tbl_sts.setGeometry(QtCore.QRect(90, 100, 1000, 471))
        self.tbl_sts.setObjectName("tbl_sts")
        self.tbl_sts.setColumnCount(5)
        self.tbl_sts.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_sts.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_sts.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_sts.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_sts.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_sts.setHorizontalHeaderItem(4, item)
        self.btn_bck = QtWidgets.QPushButton(Status)
        self.btn_bck.setGeometry(QtCore.QRect(70, 610, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_bck.setFont(font)
        self.btn_bck.setObjectName("btn_bck")

        self.retranslateUi(Status)
        QtCore.QMetaObject.connectSlotsByName(Status)

    def retranslateUi(self, Status):
        _translate = QtCore.QCoreApplication.translate
        Status.setWindowTitle(_translate("Status", "Dialog"))
        self.lbl_appsts.setText(_translate("Status", "Application Status "))
        self.comboBox_all.setItemText(0, _translate("Status", "All"))
        self.comboBox_all.setItemText(1, _translate("Status", "Pending"))
        self.comboBox_all.setItemText(2, _translate("Status", "Approved"))
        self.comboBox_all.setItemText(3, _translate("Status", "Rejected"))
        self.pushButton.setText(_translate("Status", "Approve "))
        self.pushButton_2.setText(_translate("Status", "reject"))
        self.pushButton_3.setText(_translate("Status", "send mail"))
        item = self.tbl_sts.horizontalHeaderItem(0)
        item.setText(_translate("Status", "Full name"))
        item = self.tbl_sts.horizontalHeaderItem(1)
        item.setText(_translate("Status", "Company"))
        item = self.tbl_sts.horizontalHeaderItem(2)
        item.setText(_translate("Status", "Job Role"))
        item = self.tbl_sts.horizontalHeaderItem(3)
        item.setText(_translate("Status", "Resume"))
        item = self.tbl_sts.horizontalHeaderItem(4)
        item.setText(_translate("Status", "Status"))
        self.btn_bck.setText(_translate("Status", "Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Status = QtWidgets.QDialog()
    ui = Ui_Status()
    ui.setupUi(Status)
    Status.show()
    sys.exit(app.exec_())
