# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import mysql.connector as mc
import userdash,sys

class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(1200, 700)
        Login.setStyleSheet("background: #FFFFFF;")
        Login.setSizeGripEnabled(False)
        self.img_login = QtWidgets.QLabel(Login)
        self.img_login.setGeometry(QtCore.QRect(0, 80, 641, 531))
        self.img_login.setStyleSheet("image: url(:/all/img/login.jpg);")
        self.img_login.setObjectName("img_login")
        self.lbl_welcm = QtWidgets.QLabel(Login)
        self.lbl_welcm.setGeometry(QtCore.QRect(830, 110, 231, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_welcm.setFont(font)
        self.lbl_welcm.setObjectName("lbl_welcm")
        self.labelResult = QtWidgets.QLabel(Login)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelResult.setFont(font)
        self.labelResult.setText("")
        self.labelResult.setObjectName("labelResult")

        self.txt_usern = QtWidgets.QTextEdit(Login)
        self.txt_usern.setGeometry(QtCore.QRect(740, 220, 371, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.txt_usern.setFont(font)
        self.txt_usern.setStyleSheet("border: 2px solid #000000;\n"
"border-radius: 20px;")
        self.txt_usern.setObjectName("txt_usern")
        self.btn_signin = QtWidgets.QPushButton(Login)
        self.btn_signin.setGeometry(QtCore.QRect(750, 430, 341, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_signin.setFont(font)
        self.btn_signin.setStyleSheet("border: 2px solid #000000;\n"
"border-radius: 20px;")
        self.btn_signin.setObjectName("btn_signin")
        self.btn_signin.clicked.connect(self.login)
        self.btn_reg = QtWidgets.QPushButton(Login)
        self.btn_reg.setGeometry(QtCore.QRect(810, 530, 231, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.btn_reg.setFont(font)
        self.btn_reg.setStyleSheet("border: 2px solid #000000;\n"
"border-radius: 20px;")
        self.btn_reg.setObjectName("btn_reg")
        self.lineEdit = QtWidgets.QLineEdit(Login)
        self.lineEdit.setGeometry(QtCore.QRect(740, 330, 371, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("border: 2px solid #000000;\n"
"border-radius: 20px;")
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Dialog"))
        self.img_login.setText(_translate("Login", "<html><head/><body><p><br/></p></body></html>"))
        self.lbl_welcm.setText(_translate("Login", "WELCOME"))
        self.txt_usern.setHtml(_translate("Login", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:16pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt; font-weight:400;\"><br /></p></body></html>"))
        self.txt_usern.setPlaceholderText(_translate("Login", "            Username"))
        self.btn_signin.setText(_translate("Login", "SIGN IN"))
        self.btn_reg.setText(_translate("Login", "New User ? Register Here..."))
        self.lineEdit.setPlaceholderText(_translate("Login", "Password"))

    def login(self):
        try:
            usrname = self.txt_usern.text()
            pwd = self.lineEdit.text()

            mydb = mc.connect(
                host="localhost",
                user="root",
                password="",
                database="placement"


            )

            mycursor = mydb.cursor()
            query = "SELECT usrname,pwd from acc where usrname " \
                    "like '"+usrname + "'and pwd like '" \
                    + pwd + "'"
            mycursor.execute(query)
            result = mycursor.fetchone()

            if result == None:
                self.labelResult.setText("Incorrect email or password")

            else:
                self.labelResult.setText("You are logged in")
                mydialog =QMessageBox()
                mydialog.setModal(True)
                mydialog.exec_()


        except mc.Error as e:
            self.labelResult.setText("Error")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login = QtWidgets.QDialog()
    ui = Ui_Login()
    ui.setupUi(Login)
    Login.show()
    sys.exit(app.exec_())
