# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector as mc
from PyQt5.QtWidgets import QMessageBox


class Ui_reg(object):
    def setupUi(self, ui_login):
        ui_login.setObjectName("ui_login")
        ui_login.resize(1200, 700)
        ui_login.setStyleSheet("background:#D8F8E8;")
        self.horizontalLayoutWidget = QtWidgets.QWidget(ui_login)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 20, 1121, 71))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_nme = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Typewriter")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_nme.setFont(font)
        self.lbl_nme.setObjectName("lbl_nme")
        self.horizontalLayout.addWidget(self.lbl_nme)
        self.fnme = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.fnme.setFont(font)
        self.fnme.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.fnme.setObjectName("fnme")
        self.horizontalLayout.addWidget(self.fnme)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(ui_login)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(40, 420, 1121, 71))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lbl_pswd = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Typewriter")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_pswd.setFont(font)
        self.lbl_pswd.setObjectName("lbl_pswd")
        self.horizontalLayout_2.addWidget(self.lbl_pswd)
        self.pswd = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pswd.setFont(font)
        self.pswd.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.pswd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pswd.setObjectName("pswd")
        self.horizontalLayout_2.addWidget(self.pswd)
        self.btn_reg = QtWidgets.QPushButton(ui_login)
        self.btn_reg.clicked.connect(self.database)
        self.btn_reg.setGeometry(QtCore.QRect(400, 610, 369, 41))
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        font.setPointSize(20)
        self.btn_reg.setFont(font)
        self.btn_reg.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border: 2px solid #000000;\n"
"border-radius: 20px;\n"
"")
        self.btn_reg.setObjectName("btn_reg")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(ui_login)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(30, 520, 1121, 61))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.labelresult = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.labelresult.setFont(font)
        self.labelresult.setText("")
        self.labelresult.setObjectName("labelresult")
        self.horizontalLayout_3.addWidget(self.labelresult)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(ui_login)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(40, 120, 1121, 71))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lbl_uid = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Typewriter")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_uid.setFont(font)
        self.lbl_uid.setObjectName("lbl_uid")
        self.horizontalLayout_4.addWidget(self.lbl_uid)
        self.uname = QtWidgets.QLineEdit(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.uname.setFont(font)
        self.uname.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.uname.setObjectName("uname")
        self.horizontalLayout_4.addWidget(self.uname)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(ui_login)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(40, 320, 1121, 71))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lbl_mno = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Typewriter")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_mno.setFont(font)
        self.lbl_mno.setObjectName("lbl_mno")
        self.horizontalLayout_5.addWidget(self.lbl_mno)
        self.mobileno = QtWidgets.QLineEdit(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.mobileno.setFont(font)
        self.mobileno.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.mobileno.setObjectName("mobileno")
        self.horizontalLayout_5.addWidget(self.mobileno)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(ui_login)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(40, 220, 1121, 71))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lbl_eid = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Typewriter")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_eid.setFont(font)
        self.lbl_eid.setObjectName("lbl_eid")
        self.horizontalLayout_6.addWidget(self.lbl_eid)
        self.email = QtWidgets.QLineEdit(self.horizontalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.email.setFont(font)
        self.email.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.email.setObjectName("email")
        self.horizontalLayout_6.addWidget(self.email)

        self.retranslateUi(ui_login)
        QtCore.QMetaObject.connectSlotsByName(ui_login)

    def retranslateUi(self, ui_login):
        _translate = QtCore.QCoreApplication.translate
        ui_login.setWindowTitle(_translate("ui_login", "Dialog"))
        self.lbl_nme.setText(_translate("ui_login", "Full Name"))
        self.lbl_pswd.setText(_translate("ui_login", "Password"))
        self.btn_reg.setText(_translate("ui_login", "SIGN IN"))
        self.lbl_uid.setText(_translate("ui_login", "UserID"))
        self.lbl_mno.setText(_translate("ui_login", "Mobile No."))
        self.lbl_eid.setText(_translate("ui_login", "Email ID"))

    def database(self):
        try:
            fname = self.fnme.text()
            username = self.uname.text()
            mobileno = self.mobileno.text()
            email = self.email.text()
            password = self.pswd.text()

            mydb = mc.connect(
                host="localhost",
                user="root",
                password="",
                database="placement"

            )

            mycursor = mydb.cursor()
            query = "INSERT INTO register(fname,usrname,eid,mno,pwd) values ('" + fname + "','" + username + "','" + email + "','" + mobileno + "','" + password + "')"
            a = mycursor.execute(query)

            mydb.commit()

            if a == None:
                self.labelresult.setText("You Have Successfully Registered")
                mydialog = QMessageBox()
                mydialog.setModal(True)
                mydialog.exec_()
            else:
                self.labelresult.setText("add your details")







        except mc.Error as e:
            self.labelresult.setText("Error")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ui_login = QtWidgets.QDialog()
    ui = Ui_reg()
    ui.setupUi(ui_login)
    ui_login.show()
    sys.exit(app.exec_())
